name: figma_squircle
description: A new Flutter package project.
version: 0.5.5
homepage: https://github.com/aloisdeniel/figma_squircle
publish_to: https://dart.cloudsmith.io/digizorg/default/

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  vector_math: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: {}